# @site_url@
<VirtualHost *:80>

    ServerAdmin webmaster@kessel

    DocumentRoot "@site_docroot@/@install_dir@"
    ServerName @site_url@
    ServerAlias www.@site_url@

    ErrorLog "@site_docroot@/logs/@site_url@-error_log.log"
    CustomLog "@site_docroot@/logs/@site_url@-access_log.log" common

    <Directory "@site_docroot@/@install_dir@">
        RewriteEngine On
        # match any URL with www and rewrite it to https without the www
        RewriteCond %{HTTP_HOST} ^(www\.)(.*) [NC]
        RewriteRule (.*) https://%2%{REQUEST_URI} [L,R=301]

      Options Indexes MultiViews FollowSymLinks
      AllowOverride All
      Require all granted
    </Directory>

</VirtualHost>