# @site_url@
<VirtualHost *:80>

    ServerAdmin webmaster@kessel

    DocumentRoot "@site_docroot@/@install_dir@"
    ServerName @site_url@
    ServerAlias www.@site_url@

    ErrorLog "@site_docroot@/logs/@site_url@-error_log.log"
    CustomLog "@site_docroot@/logs/@site_url@-access_log.log" common

    <Directory "@site_docroot@/@install_dir@">
      Options Indexes MultiViews 
      AllowOverride None
      Require all granted
    </Directory>

RewriteEngine on
RewriteCond %{SERVER_NAME} =www.@site_url@ [OR]
RewriteCond %{SERVER_NAME} =@site_url@
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

</VirtualHost>