# @site_url@
<VirtualHost *:80>

    ServerAdmin webmaster@kessel

    DocumentRoot "@site_docroot@/public_html/"
    ServerName @site_url@
    ServerAlias www.@site_url@

    ErrorLog "@site_docroot@/logs/@site_url@-error_log.log"
    CustomLog "@site_docroot@/logs/@site_url@-access_log.log" common

    <Directory "@site_docroot@/public_html">
      Options Indexes FollowSymLinks MultiViews
      Require all granted
      AllowOverride All
    </Directory>

</VirtualHost>